[build]
  publish = "."
  functions = "netlify/functions"
  command = "echo no-build"

[functions]
  node_bundler = "zisi"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive"
